# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 03:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('singleSignOn', '0002_auto_20161031_1249'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='idlusers',
            table='idlusers',
        ),
    ]
